query Products{
  products{
    data{
      id
      attributes{
        title
        description
        price
        image{
          data{
            attributes{
              url
            }
          }
        }
        custom_field{
          title
          required
          options
          small
          medium
          large
          XL
          twoXL
          threeXL
        }
      }
    }
  }
}